name: Create GitHub Release

on:
  workflow_dispatch:
    branches:
      - master

env:
  DEB_BUILD_DOCKER_IMAGE: "pitop/pi-top-os-deb-build"
  DEB_BUILD_DOCKER_TAG: "latest"
  PACKAGECLOUD_REPO: "pi-top-os-unstable"
  OS: "debian"
  DISTRO: "bullseye"

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.3

      # TODO: move this to a new action
      # (use Docker for pre-installing 'dpkg-dev')
      - name: Confirm version is higher than last tagged version
        run: |
          set -x
          sudo apt install -y dpkg-dev
          latest_tag=${{ steps.version.outputs.tag_latest }}
          latest_version=$(dpkg-parsechangelog -Sversion)
          dpkg --compare-versions ${latest_version} gt ${latest_tag#v}
          echo "CURRENT_VERSION=${latest_version}" >> $GITHUB_ENV

      - name: Determine architecture to use from package info
        # If architecture is 'all', then it can be compiled on host architecture
        # All other pi-topOS cases require 'armhf'
        run: |
          target_architecture=amd64
          if grep '^Architecture:' debian/control | grep -q -v 'all'; then
            target_architecture=armhf
          fi
          echo "TARGET_ARCHITECTURE=${target_architecture}" >> $GITHUB_ENV

      - name: Build Debian package
        uses: pi-top/debian-package-build-action@master
        with:
          target_architecture: ${{ env.TARGET_ARCHITECTURE }}
          docker_image: ${{ env.DEB_BUILD_DOCKER_IMAGE }}:${{ env.DEB_BUILD_DOCKER_TAG }}
          build_directory: ./artifacts
          # Optional, repo-specific build environment variables
          additional_env: |
            DATA="${{ secrets.DATA }}"
            TLS_KEY="${{ secrets.TLS_KEY }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "dsc"
          path: "./artifacts"

      - uses: pi-top/ghaction-packagecloud@main
        with:
          repository: ${{ env.PACKAGECLOUD_REPO }}/${{ env.OS }}/${{ env.DISTRO }}
          files: |
            ./artifacts/*.dsc
            ./artifacts/*.deb
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.CURRENT_VERSION }}"
          name: "v${{ env.CURRENT_VERSION }}"
          draft: false
          prerelease: false
          files: ./artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
