name: Package Quality Check

on:
  push:
  schedule:
    # Run daily at midnight
    - cron:  '0 0 * * *'

jobs:
  check-package:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository submodules
        uses: actions/checkout@v2.2.0

      - name: Install meta
        run: |
          sudo npm i -g meta

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GH_SERVICE_ACCT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Clone repositories using meta
        run: |
          meta git update

      - name: Show directory content
        run: |
          meta exec "ls -l" --parallel

      - name: Check that latest entry is listed correctly
        run: |
          meta exec "[[ ! -f debian/changelog ]] && { echo 'No changelog'; }         || { head -n1 debian/changelog | grep -q 'buster'         && { echo 'Distribution: OK'; } || { echo 'Distribution: Not OK'; }; }"             --parallel
          meta exec "[[ ! -f debian/changelog ]] && { echo 'No changelog'; }         || { head -n1 debian/changelog | grep -q 'urgency=medium' && { echo 'Urgency: OK'; }      || { echo 'Urgency: Not OK'; }; }"                  --parallel
          meta exec "[[ ! -f debian/clean ]]     && { echo 'No debian/clean file'; } || { head -n1 debian/clean     | grep -q 'Jenkinsfile'    && { echo 'clean file: OK'; }   || { echo 'clean file: Missing 'Jenkinsfile'; }; }" --parallel
          meta exec "[[ ! -f debian/clean ]]     && { echo 'No debian/clean file'; } || { head -n1 debian/clean     | grep -q '.git'           && { echo 'clean file: OK'; }   || { echo 'clean file: Missing '.git'; }; }"        --parallel
